kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mt-saas-api
nodes:
  - role: control-plane
    image: kindest/node:v1.37.0@sha256:a1ed56cfb0e7b93589bdf97c8cd566405a265939e3620fc4f5de89adff580ae5
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # 30081 is the java service
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
  - role: worker
    image: kindest/node:v1.37.0@sha256:a1ed56cfb0e7b93589bdf97c8cd566405a265939e3620fc4f5de89adff580ae5
