apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migrate
  namespace: mt-saas-api
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alembic-migrate
          image: ghcr.io/akshitanchan/mt-saas-api:dev
          imagePullPolicy: IfNotPresent
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
